### ISSUE TITLE
Create in non-dom context

### ISSUE THREAD

**Issue by dy** [hyperdivision/fast-on-load#6]
This lib can be useful in [jsdom](https://ghub.io/jsdom), [dom-lite](https://ghub.io/dom-lite) or [min-document](https://ghub.io/min-document) contexts, running in nodejs for example.

What's the best way to make it work?
Should there be a slight code change to support them, eg.
```js
import { document } from 'dom-lite'
import onload from 'fast-on-load'

let _onload = onload.bind(document)
```

**Comment by bcomnes** [comment]
If that works, we can make note of it in the readme.  lmkwyt

**Comment by dy** [comment]
It doesn’t work now, needs small refactoring - I could come up with little change for that

**Comment by bcomnes** [comment]
Yeah open to it.
